version: '3'
services:
  server:
    image: py_messenger-image:latest
    container_name: py_messenger-container
    build:
      context: .
      args:
        SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
        SERVER_PORT: ${SERVER_PORT:-5000}
    environment:
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      SERVER_PORT: ${SERVER_PORT:-5000}
    ports:
      - "${SERVER_PORT:-5000}:${SERVER_PORT:-5000}"
    volumes:
      - ./data/:/app/data/